Subject = u"Smartsheets"
From = u"do-not-reply@nips.cc"
default_filename = u"Access.xlsx"
smartsheet_manager = u"Terrence Gaines <terrence.gaines@hp.com>"
log_format = ".isoformat()"
date_format = u"%Y-%m-%d %H:%M"
redirect_emails_to = u"terrence.gaines@hp.com"  #Normally an empty string.  Set to your email address to send all output to you. 
stop_after = 0  #Set this to zero to send all emails. 
format='WVpFLWFkUi02SlEtcm80'
