Subject = u"Smartsheets"
From = u"do-not-reply@nips.cc"
default_filename = u"Access.xlsx"
smartsheet_manager = u"Terrence Gaines <terrence.gaines@hp.com>"
log_format = ".isoformat()"
date_format = u"%Y-%m-%d %H:%M"
